### ISSUE TITLE
Support relative package names

### ISSUE THREAD

**Issue by timstclair** [google/godepq#2]
e.g. this should work:

```
$ cd go/src/k8s.io/kubernetes
$ godepq -from ./pkg/kubelet -to ./pkg/probe
```

**Comment by caesarxuchao** [comment]
sub/

**Comment by dmitshur** [comment]
Can this be done just by resolving the relative import paths to full using cwd?

**Edit:** I see there's already some code to do that, e.g., [here](https://github.com/google/godepq/blob/8972cece5269b1cb4cf5f34527cc735e59e997e6/godepq.go#L43-L45) and [here](https://github.com/google/godepq/blob/8972cece5269b1cb4cf5f34527cc735e59e997e6/pkg/deps.go#L85). But it appears it's not enough to make things work, because some of the code other than loading the package depends/assumes full import paths rather than relative.

Perhaps it's reasonable to fix this issue by resolving relative import paths to full import paths as part of pre-processing, so the rest of the code always deals with full import paths. What do you think?

**Comment by dmitshur** [comment]
I've created #3 that should resolve this issue, please take a look.
